

export const WIZARD_STATE_UPLOAD = "WIZARD_STATE_UPLOAD"

export const WIZARD_STATE_VERSION_CHECK_LOADING = "WIZARD_STATE_VERSION_CHECK_LOADING"
export const WIZARD_STATE_VERSION_CHECK_UPDATE = "WIZARD_STATE_VERSION_CHECK_UPDATE"
export const WIZARD_STATE_VERSION_CHECK_INSTALL = "WIZARD_STATE_VERSION_CHECK_INSTALL"
export const WIZARD_STATE_VERSION_CHECK_INSTALL_EXTENSION = "WIZARD_STATE_VERSION_CHECK_INSTALL_EXTENSION"


export const WIZARD_STATE_CERTIFICATES_LOADING = "WIZARD_STATE_CERTIFICATES_LOADING"
export const WIZARD_STATE_CERTIFICATES_CHOOSE = "WIZARD_STATE_CERTIFICATES_CHOOSE"


export const WIZARD_STATE_VALIDATE_LOADING = "WIZARD_STATE_VALIDATE_LOADING"
export const WIZARD_STATE_VALIDATE_NOTVALID = "WIZARD_STATE_VALIDATE_NOTVALID"


export const WIZARD_STATE_DIGEST_LOADING = "WIZARD_STATE_DIGEST_LOADING"
export const WIZARD_STATE_SIGNING_LOADING = "WIZARD_STATE_SIGNING_LOADING"
export const WIZARD_STATE_SIGNINGDOC_LOADING = "WIZARD_STATE_SIGNINGDOC_LOADING"

export const WIZARD_STATE_PIN_INPUT = "WIZARD_STATE_PIN_INPUT"
export const WIZARD_STATE_PIN_PAD = "WIZARD_STATE_PIN_PAD"

export const WIZARD_STATE_SUCCES = "WIZARD_STATE_SUCCES"
export const WIZARD_STATE_ERROR = "WIZARD_STATE_ERROR"
export const WIZARD_STATE_INFO = "WIZARD_STATE_INFO"
export const WIZARD_STATE_MESSAGE = "WIZARD_STATE_MESSAGE"

export const WIZARD_STATE_SIGNING_PRESIGN_LOADING = "WIZARD_STATE_SIGNING_PRESIGN_LOADING"
export const WIZARD_STATE_PINPAD_ERROR = "WIZARD_STATE_PINPAD_ERROR"

export const WIZARD_STATE_START = "WIZARD_STATE_START"
export const WIZARD_STATE_RESULT = "WIZARD_STATE_RESULT"


export const WIZARD_STATE_CERTIFICATES_VALIDATE_CHAIN = "WIZARD_STATE_CERTIFICATES_VALIDATE_CHAIN"